name: "🤖 Merge: Dependabot PR"

on:
  pull_request:
    branches:
      - main

permissions:
  contents: write

env:
  # This is required to use the 'gh' CLI in actions.
  GH_TOKEN: ${{ github.token }}

jobs:
  # See https://docs.github.com/en/code-security/dependabot/working-with-dependabot/automating-dependabot-with-github-actions#enable-auto-merge-on-a-pull-request.
  dependabot:
    if: |
      github.event_name == 'pull_request' &&
      github.actor == 'dependabot[bot]'

    runs-on: ubuntu-latest
    timeout-minutes: 1

    steps:
      - name: Dependabot metadata
        id: metadata
        uses: dependabot/fetch-metadata@v2
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"

      - name: Enable auto-merge for Dependabot PRs
        if: steps.metadata.outputs.update-type == 'version-update:semver-patch'
        run: gh pr merge --auto --squash "${{ github.event.pull_request.html_url }}"